#!/bin/bash
########################################################################
#APONWAO FRAMEWORK
#Copyright (C) 2009 Coral Vision Systems
#
#Developers:
#Juan Scarton <jscarton@aponwaophp.org>
#Rafael Vivas <rvivas@aponwaophp.org>
#Saul Bautista <sbautista@aponwaophp.org>
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program. If not, see <http://www.gnu.org/licenses/>.
########################################################################
echo "Aponwao Developer Tools (c) 2009, Proyecto Aponwao"
echo "v.0.1.x"
echo "<http://aponwaophp.org>"
echo "--------------------------------------------------"
echo ""
echo "Copiando archivo base..."
cp /usr/share/aponwao-tools/aponwaophp.tar.gz ./
echo "descomprimiendo archivo base..."
tar xvzf aponwaophp.tar.gz
echo "asignando permisos de desarrollo..."
chmod 777 -v -R ./
echo "borrando archivos temporales..."
rm -f aponwaophp.tar.gz